name:                haskell-status
version:             0.1.0.0
github:              "githubuser/haskell-status"
license:             BSD3
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2022 Author name here"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/haskell-status#readme>

dependencies:
- base >= 4.7 && < 5

  #library:
  #  source-dirs: src

executables:
  haskell-status-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    default-extensions: 
    - LambdaCase 
    - ImportQualifiedPost
    - NamedFieldPuns
    - RecordWildCards
    - OverloadedStrings
    - DefaultSignatures
    - FlexibleContexts
    - TypeSynonymInstances
    - DataKinds
    - GADTs
    - PolyKinds
    - RankNTypes
    - ScopedTypeVariables
    - TypeApplications
    - TypeOperators
    - TypeFamilies
    - FlexibleInstances
    dependencies: 
      - process
      - extra
      - tomland
      - containers
      - generic-data
      - text
      - netlink >= 1.1.1.0
      - cereal >= 0.5.8.0
      - timezone-olson >= 0.2 && < 0.3 
      - timezone-series == 0.1.*
      - transformers
      - bytestring
      - unix
      - hformat 
      - directory
      - network-info
      - time
      - one-liner
      - ansi-terminal
      - polysemy
      - lens
      - aeson
      - hinotify 
      - unordered-containers
      - async
      - dbus
